CREATE TABLE [dbo].[FavoriteNewsItem]
(
	[Id] INT NOT NULL PRIMARY KEY NONCLUSTERED IDENTITY,
	[NewsItemId] UNIQUEIDENTIFIER NOT NULL,
	[UserId] UNIQUEIDENTIFIER NOT NULL,
	[FeedId] UNIQUEIDENTIFIER NOT NULL,
	[PublishDateTime] DATETIME NOT NULL,
	[SavedOn] DATETIME NOT NULL,
	[Title] VARCHAR(MAX) NOT NULL, 
	[Link] VARCHAR(MAX) NOT NULL, 
	[NewsItemBlob] VARBINARY(MAX) NOT NULL, 
)

GO
CREATE CLUSTERED INDEX [FavoriteNewsItemIndex] on [dbo].[FavoriteNewsItem] ([UserId],[Id])